scoreboard objectives add fuel dummy Fuel
scoreboard players add @s fuel 1
gamerule commandblockoutput false

execute @s[scores={fuel=0}] ~~~ title @s actionbar §a§lFuel§r: 100%
execute @s[scores={fuel=10}] ~~~ title @s actionbar §a§lFuel§r: 99%
execute @s[scores={fuel=30}] ~~~ title @s actionbar §a§lFuel§r: 98%
execute @s[scores={fuel=50}] ~~~ title @s actionbar §a§lFuel§r: 97%
execute @s[scores={fuel=70}] ~~~ title @s actionbar §a§lFuel§r: 96%
execute @s[scores={fuel=90}] ~~~ title @s actionbar §a§lFuel§r: 95%
execute @s[scores={fuel=110}] ~~~ title @s actionbar §a§lFuel§r: 94%
execute @s[scores={fuel=130}] ~~~ title @s actionbar §a§lFuel§r: 93%
execute @s[scores={fuel=150}] ~~~ title @s actionbar §a§lFuel§r: 92%
execute @s[scores={fuel=170}] ~~~ title @s actionbar §a§lFuel§r: 91%
execute @s[scores={fuel=190}] ~~~ title @s actionbar §a§lFuel§r: 90%
execute @s[scores={fuel=210}] ~~~ title @s actionbar §a§lFuel§r: 89%
execute @s[scores={fuel=230}] ~~~ title @s actionbar §a§lFuel§r: 88%
execute @s[scores={fuel=250}] ~~~ title @s actionbar §a§lFuel§r: 87%
execute @s[scores={fuel=270}] ~~~ title @s actionbar §a§lFuel§r: 86%
execute @s[scores={fuel=290}] ~~~ title @s actionbar §a§lFuel§r: 85%
execute @s[scores={fuel=310}] ~~~ title @s actionbar §a§lFuel§r: 84%
execute @s[scores={fuel=330}] ~~~ title @s actionbar §a§lFuel§r: 83%
execute @s[scores={fuel=350}] ~~~ title @s actionbar §a§lFuel§r: 82%
execute @s[scores={fuel=370}] ~~~ title @s actionbar §a§lFuel§r: 81%
execute @s[scores={fuel=390}] ~~~ title @s actionbar §a§lFuel§r: 80%
execute @s[scores={fuel=410}] ~~~ title @s actionbar §a§lFuel§r: 79%
execute @s[scores={fuel=430}] ~~~ title @s actionbar §a§lFuel§r: 78%
execute @s[scores={fuel=450}] ~~~ title @s actionbar §a§lFuel§r: 77%
execute @s[scores={fuel=470}] ~~~ title @s actionbar §a§lFuel§r: 76%
execute @s[scores={fuel=490}] ~~~ title @s actionbar §a§lFuel§r: 75%
execute @s[scores={fuel=510}] ~~~ title @s actionbar §a§lFuel§r: 74%
execute @s[scores={fuel=530}] ~~~ title @s actionbar §a§lFuel§r: 73%
execute @s[scores={fuel=550}] ~~~ title @s actionbar §a§lFuel§r: 72%
execute @s[scores={fuel=570}] ~~~ title @s actionbar §a§lFuel§r: 71%
execute @s[scores={fuel=590}] ~~~ title @s actionbar §a§lFuel§r: 70%
execute @s[scores={fuel=610}] ~~~ title @s actionbar §a§lFuel§r: 69%
execute @s[scores={fuel=630}] ~~~ title @s actionbar §a§lFuel§r: 68%
execute @s[scores={fuel=650}] ~~~ title @s actionbar §a§lFuel§r: 67%
execute @s[scores={fuel=670}] ~~~ title @s actionbar §a§lFuel§r: 66%
execute @s[scores={fuel=690}] ~~~ title @s actionbar §a§lFuel§r: 65%
execute @s[scores={fuel=710}] ~~~ title @s actionbar §a§lFuel§r: 64%
execute @s[scores={fuel=730}] ~~~ title @s actionbar §a§lFuel§r: 63%
execute @s[scores={fuel=750}] ~~~ title @s actionbar §a§lFuel§r: 62%
execute @s[scores={fuel=770}] ~~~ title @s actionbar §a§lFuel§r: 61%
execute @s[scores={fuel=790}] ~~~ title @s actionbar §a§lFuel§r: 60%
execute @s[scores={fuel=810}] ~~~ title @s actionbar §a§lFuel§r: 59%
execute @s[scores={fuel=830}] ~~~ title @s actionbar §a§lFuel§r: 58%
execute @s[scores={fuel=850}] ~~~ title @s actionbar §a§lFuel§r: 57%
execute @s[scores={fuel=870}] ~~~ title @s actionbar §a§lFuel§r: 56%
execute @s[scores={fuel=890}] ~~~ title @s actionbar §a§lFuel§r: 55%
execute @s[scores={fuel=910}] ~~~ title @s actionbar §a§lFuel§r: 54%
execute @s[scores={fuel=930}] ~~~ title @s actionbar §a§lFuel§r: 53%
execute @s[scores={fuel=950}] ~~~ title @s actionbar §a§lFuel§r: 52%
execute @s[scores={fuel=970}] ~~~ title @s actionbar §a§lFuel§r: 51%
execute @s[scores={fuel=990}] ~~~ title @s actionbar §a§lFuel§r: 50%
execute @s[scores={fuel=1010}] ~~~ title @s actionbar §a§lFuel§r: 49%
execute @s[scores={fuel=1030}] ~~~ title @s actionbar §a§lFuel§r: 48%
execute @s[scores={fuel=1050}] ~~~ title @s actionbar §a§lFuel§r: 47%
execute @s[scores={fuel=1070}] ~~~ title @s actionbar §a§lFuel§r: 46%
execute @s[scores={fuel=1090}] ~~~ title @s actionbar §a§lFuel§r: 45%
execute @s[scores={fuel=1110}] ~~~ title @s actionbar §a§lFuel§r: 44%
execute @s[scores={fuel=1130}] ~~~ title @s actionbar §a§lFuel§r: 43%
execute @s[scores={fuel=1150}] ~~~ title @s actionbar §a§lFuel§r: 42%
execute @s[scores={fuel=1170}] ~~~ title @s actionbar §a§lFuel§r: 41%
execute @s[scores={fuel=1190}] ~~~ title @s actionbar §a§lFuel§r: 40%
execute @s[scores={fuel=1210}] ~~~ title @s actionbar §a§lFuel§r: 39%
execute @s[scores={fuel=1230}] ~~~ title @s actionbar §a§lFuel§r: 38%
execute @s[scores={fuel=1250}] ~~~ title @s actionbar §a§lFuel§r: 37%
execute @s[scores={fuel=1270}] ~~~ title @s actionbar §a§lFuel§r: 36%
execute @s[scores={fuel=1290}] ~~~ title @s actionbar §a§lFuel§r: 35%
execute @s[scores={fuel=1310}] ~~~ title @s actionbar §a§lFuel§r: 34%
execute @s[scores={fuel=1330}] ~~~ title @s actionbar §a§lFuel§r: 33%
execute @s[scores={fuel=1350}] ~~~ title @s actionbar §a§lFuel§r: 32%
execute @s[scores={fuel=1370}] ~~~ title @s actionbar §a§lFuel§r: 31%
execute @s[scores={fuel=1390}] ~~~ title @s actionbar §a§lFuel§r: 30%
execute @s[scores={fuel=1410}] ~~~ title @s actionbar §a§lFuel§r: 29%
execute @s[scores={fuel=1430}] ~~~ title @s actionbar §a§lFuel§r: 28%
execute @s[scores={fuel=1450}] ~~~ title @s actionbar §a§lFuel§r: 27%
execute @s[scores={fuel=1470}] ~~~ title @s actionbar §a§lFuel§r: 26%
execute @s[scores={fuel=1490}] ~~~ title @s actionbar §a§lFuel§r: 25%
execute @s[scores={fuel=1510}] ~~~ title @s actionbar §a§lFuel§r: 24%
execute @s[scores={fuel=1530}] ~~~ title @s actionbar §a§lFuel§r: 23%
execute @s[scores={fuel=1550}] ~~~ title @s actionbar §a§lFuel§r: 22%
execute @s[scores={fuel=1570}] ~~~ title @s actionbar §a§lFuel§r: 21%
execute @s[scores={fuel=1590}] ~~~ title @s actionbar §a§lFuel§r: 20%
execute @s[scores={fuel=1610}] ~~~ title @s actionbar §a§lFuel§r: 19%
execute @s[scores={fuel=1630}] ~~~ title @s actionbar §a§lFuel§r: 18%
execute @s[scores={fuel=1650}] ~~~ title @s actionbar §a§lFuel§r: 17%
execute @s[scores={fuel=1670}] ~~~ title @s actionbar §a§lFuel§r: 16%
execute @s[scores={fuel=1690}] ~~~ title @s actionbar §a§lFuel§r: §e15%
execute @s[scores={fuel=1710}] ~~~ title @s actionbar §a§lFuel§r: §e14%
execute @s[scores={fuel=1730}] ~~~ title @s actionbar §a§lFuel§r: §e13%
execute @s[scores={fuel=1750}] ~~~ title @s actionbar §a§lFuel§r: §e12%
execute @s[scores={fuel=1770}] ~~~ title @s actionbar §a§lFuel§r: §e11%
execute @s[scores={fuel=1790}] ~~~ title @s actionbar §a§lFuel§r: §610%
execute @s[scores={fuel=1810}] ~~~ title @s actionbar §a§lFuel§r: §69%
execute @s[scores={fuel=1830}] ~~~ title @s actionbar §a§lFuel§r: §68%
execute @s[scores={fuel=1850}] ~~~ title @s actionbar §a§lFuel§r: §67%
execute @s[scores={fuel=1870}] ~~~ title @s actionbar §a§lFuel§r: §66%
execute @s[scores={fuel=1890}] ~~~ title @s actionbar §a§lFuel§r: §45%
execute @s[scores={fuel=1910}] ~~~ title @s actionbar §a§lFuel§r: §44%
execute @s[scores={fuel=1930}] ~~~ title @s actionbar §a§lFuel§r: §43%
execute @s[scores={fuel=1950}] ~~~ title @s actionbar §a§lFuel§r: §42%
execute @s[scores={fuel=1970}] ~~~ title @s actionbar §a§lFuel§r: §41%
execute @s[scores={fuel=1990}] ~~~ title @s actionbar §a§lFuel§r: §4Empty!
execute @s[scores={fuel=1990}] ~~~ replaceitem entity @s slot.armor.chest 1 prototype:jetpack_empty
execute @s[scores={fuel=1990}] ~~~ playsound random.break @s ~~~ 25
execute @s[scores={fuel=1990}] ~~~ playsound beacon.deactivate @s ~~~ 0.4 0.5 
execute @s[scores={fuel=1990}] ~~~ clear @s prototype:jetpack 0 1