execute @s[scores={fuel=1990}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=1991}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=1992}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=1993}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=1994}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=1995}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=1996}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=1997}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=1998}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=1999}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2000}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2001}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2002}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2003}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2004}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2005}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2006}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2007}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2008}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2009}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2010}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2011}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2012}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2013}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2014}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2015}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2016}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2017}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2019}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2020}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2021}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2022}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2023}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2024}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2025}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2026}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2027}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2028}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2029}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2030}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2031}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2032}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2033}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2034}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2035}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2036}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2037}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2038}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2039}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2040}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2041}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2042}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2043}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2044}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2045}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2046}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2047}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2048}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2049}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2050}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2051}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2052}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2053}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2054}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2055}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2056}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2057}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2058}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2059}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2060}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2061}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2062}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2063}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2064}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2065}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2066}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2067}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2068}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2069}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2070}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2071}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2072}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2073}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2074}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2075}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2076}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2077}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2078}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2079}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2080}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2081}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2082}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2083}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2084}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2085}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2086}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2087}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2088}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2089}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2090}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2091}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2092}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2093}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2094}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2095}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2096}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2097}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2098}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2099}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2100}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2101}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2102}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2103}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2104}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2105}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2106}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2107}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2108}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2109}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2110}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2111}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2112}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2113}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2114}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2115}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2116}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2117}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2118}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2119}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2120}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2121}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2122}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2123}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2124}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2125}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2126}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2127}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2128}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2129}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2130}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2131}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2132}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2133}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2134}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2135}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2136}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2137}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2138}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2139}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2140}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2141}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2142}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2143}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2144}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2145}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2146}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2147}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2148}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2149}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2150}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2151}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2152}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2153}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2154}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2155}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2156}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2157}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2158}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2159}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2160}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2161}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2162}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2163}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2164}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2165}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2166}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2167}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2168}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2169}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2170}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2171}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2172}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2173}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2174}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2175}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2176}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2177}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2178}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2179}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2180}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2181}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2182}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2183}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2184}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2185}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2186}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2187}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2188}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2189}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2190}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2191}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2192}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2193}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2194}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2195}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2196}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2197}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2198}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2199}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2200}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2201}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2202}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2203}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2204}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2205}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2206}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2207}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2208}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2209}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2210}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2211}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2212}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2213}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2214}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2215}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2216}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2217}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2218}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2219}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2220}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2221}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2222}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2223}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2224}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2225}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2226}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2227}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2228}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2229}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2230}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2231}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2232}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2233}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2234}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2235}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2236}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2237}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2238}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2239}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2240}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2241}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2242}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2243}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2244}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2245}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2246}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2247}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2248}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2249}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2250}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2251}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2252}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2253}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2254}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2255}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2256}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2257}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2258}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2259}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2260}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2261}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2262}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2263}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2264}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2265}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2266}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2267}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2268}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2269}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2270}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2271}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2272}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2273}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2274}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2275}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2276}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2277}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2278}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2279}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2280}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2281}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2282}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2283}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2284}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2285}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2286}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2287}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2288}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2289}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2290}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2291}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2292}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2293}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2294}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2295}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2296}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2297}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2298}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2299}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2300}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2301}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2302}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2303}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2304}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2305}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2306}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2307}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2308}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2309}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2310}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2311}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2312}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2313}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2314}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2315}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2316}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2317}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2318}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2319}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2320}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2321}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2322}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2323}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2324}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2325}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2326}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2327}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2328}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2329}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2330}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2331}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2332}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2333}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2334}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2335}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2336}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2337}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2338}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2339}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2340}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2341}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2342}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2343}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2344}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2345}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2346}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2347}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2348}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2349}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2350}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2351}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2352}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2353}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2354}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2355}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2356}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2357}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2358}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2359}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2360}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2361}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2362}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2363}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2364}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2365}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2366}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2367}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2368}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2369}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2370}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2371}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2372}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2373}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2374}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2375}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2376}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2377}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2378}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2379}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2380}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2381}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2382}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2383}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2384}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2385}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2386}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2387}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2388}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2389}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2390}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2391}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2392}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2393}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2394}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2395}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2396}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2397}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2398}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2399}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2400}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2401}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2402}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2403}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2404}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2405}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2406}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2407}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2408}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2409}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2410}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2411}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2412}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2413}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2414}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2415}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2416}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2417}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2418}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2419}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2420}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2421}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2422}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2423}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2424}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2425}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2426}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2427}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2428}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2429}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2430}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2431}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2432}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2433}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2434}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2435}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2436}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2437}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2438}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2439}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2440}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2441}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2442}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2443}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2444}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2445}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2446}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2447}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2448}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2449}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2450}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2451}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2452}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2453}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2454}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2455}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2456}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2457}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2458}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2459}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2460}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2461}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2462}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2463}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2464}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2465}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2466}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2467}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2468}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2469}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2470}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2471}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2472}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2473}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2474}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2475}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2476}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2477}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2478}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2479}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2480}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2481}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2482}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2483}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2484}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2485}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2486}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2487}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2488}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2489}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2490}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2491}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2492}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2493}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2494}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2495}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2496}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2497}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2498}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2499}] ~ ~ ~ scoreboard players set @s fuel 0
execute @s[scores={fuel=2500}] ~ ~ ~ scoreboard players set @s fuel 0